twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths: 
        '%kernel.project_dir%/src/AppCommon/Application/Resources/views': domain_common_resources
        '%kernel.project_dir%/src/UserManagement/Application/Resources/views': user_management_resources
