user_management_login:
    path: /user/login
    defaults: { _controller: UserManagement\Application\Controller\LoginController::indexAction }
    methods: [GET, HEAD]
user_management_login_submit:
    path: /user/login
    defaults: { _controller: UserManagement\Application\Controller\LoginController::submitAction }
    methods: [POST]
user_management_register:
    path: /user/register
    defaults: { _controller: UserManagement\Application\Controller\RegistrationController::indexAction }
    methods: [GET, HEAD]
user_management_register_create:
    path: /user/register
    defaults: { _controller: UserManagement\Application\Controller\RegistrationController::createAction }
    methods: [POST]
user_management_logout:
    path: /user/logout
    defaults: { _controller: UserManagement\Application\Controller\LogoutController::logoutAction }
    methods: [GET, HEAD]


user_management:
    path: /user/
    defaults: { _controller: UserManagement\Application\Controller\UserController::indexAction }
    methods: [GET, HEAD]
user_management_get_list:
    path: /user/get-list
    defaults: { _controller: UserManagement\Application\Controller\UserController::getListAction }
    methods: [GET, HEAD]
user_management_delete:
    path: /user/delete
    defaults: { _controller: UserManagement\Application\Controller\UserController::deleteAction }
    methods: [POST]
user_management_edit:
    path: /user/edit
    defaults: { _controller: UserManagement\Application\Controller\UserController::editAction }
    methods: [POST]
user_management_enable_admin:
    path: /user/enable-admin
    defaults: { _controller: UserManagement\Application\Controller\UserController::enableAdminAction }
    methods: [POST]


expense_management:
    path: /expense/
    defaults: { _controller: ExpenseManagement\Application\Controller\ExpenseController::indexAction }
    methods: [GET, HEAD]
expense_management_get_list:
    path: /expense/get-list
    defaults: { _controller: ExpenseManagement\Application\Controller\ExpenseController::getListAction }
    methods: [GET, HEAD]
expense_management_delete:
    path: /expense/delete
    defaults: { _controller: ExpenseManagement\Application\Controller\ExpenseController::deleteAction }
    methods: [POST]
expense_management_edit:
    path: /expense/edit
    defaults: { _controller: ExpenseManagement\Application\Controller\ExpenseController::editAction }
    methods: [POST]
expense_management_add:
    path: /expense/add
    defaults: { _controller: ExpenseManagement\Application\Controller\ExpenseController::addAction }
    methods: [POST]
expense_management_get_total_expenses:
    path: /expense/get-total-expenses
    defaults: { _controller: ExpenseManagement\Application\Controller\ExpenseController::getTotalExpensesAction }
    methods: [GET, HEAD]
expense_management_get_total_days:
    path: /expense/get-total-days
    defaults: { _controller: ExpenseManagement\Application\Controller\ExpenseController::getTotalDaysAction }
    methods: [GET, HEAD]

