services:

    Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder:
        arguments:
            $cost: 8

    DomainCommon\:
        autowire: true
        public: true
        resource: '../../../src/DomainCommon/*'
        exclude: '../../../src/DomainCommon/Domain/{Entity,UseCase,ValueObject}'
    DomainCommon\Domain\ValueObject\:
        public: true
        resource: '../../../src/DomainCommon/Domain/ValueObject/*'

    UserManagement\:
        autowire: true
        public: true
        resource: '../../../src/UserManagement/*'
        exclude: '../../../src/UserManagement/Domain/{Entity,UseCase,ValueObject}'
    UserManagement\Domain\Entity\:
        public: true
        resource: '../../../src/UserManagement/Domain/Entity/*'
    UserManagement\Domain\UseCase\:
        public: true
        resource: '../../../src/UserManagement/Domain/UseCase/*'
    UserManagement\Domain\ValueObject\:
        public: true
        resource: '../../../src/UserManagement/Domain/ValueObject/*'
    UserManagement\Infrastructure\Service\PasswordEncoderImpl:
        bind:
            Symfony\Component\Security\Core\Encoder\SelfSaltingEncoderInterface: '@Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder'
    UserManagement\Infrastructure\Service\UserSessionManagerImpl:
        bind:
            Symfony\Component\HttpFoundation\Session\SessionInterface: '@session'
    UserManagement\Presentation\Controller\LoginController:
        bind:
            UserManagement\Domain\Repository\UserRepository: '@UserManagement\Infrastructure\Repository\Doctrine\UserRepositoryImpl'
            UserManagement\Domain\Service\PasswordEncoder: '@UserManagement\Infrastructure\Service\PasswordEncoderImpl'
            UserManagement\Domain\Service\UserSessionManager: '@UserManagement\Infrastructure\Service\UserSessionManagerImpl'
    UserManagement\Presentation\Controller\RegistrationController:
        bind:
            UserManagement\Domain\Repository\UserRepository: '@UserManagement\Infrastructure\Repository\Doctrine\UserRepositoryImpl'
            UserManagement\Domain\Service\PasswordEncoder: '@UserManagement\Infrastructure\Service\PasswordEncoderImpl'
    UserManagement\Presentation\Controller\HomeController:
        bind:
            UserManagement\Domain\Service\UserSessionManager: '@UserManagement\Infrastructure\Service\UserSessionManagerImpl'
    UserManagement\Presentation\EventSubscriber\AuthenticationSubscriber:
        autowire: true
        bind:
            UserManagement\Domain\Service\UserSessionManager: '@UserManagement\Infrastructure\Service\UserSessionManagerImpl'
        tags: [kernel.event_subscriber]

    ExpenseManagement\:
        autowire: true
        public: true
        resource: '../../../src/ExpenseManagement/*'
        exclude: '../../../src/ExpenseManagement/Domain/{Entity,UseCase,ValueObject}'
    ExpenseManagement\Domain\Entity\:
        public: true
        resource: '../../../src/ExpenseManagement/Domain/Entity/*'
    ExpenseManagement\Domain\UseCase\:
        public: true
        resource: '../../../src/ExpenseManagement/Domain/UseCase/*'
    ExpenseManagement\Domain\ValueObject\:
        public: true
        resource: '../../../src/ExpenseManagement/Domain/ValueObject/*'

    LogManagement\:
        autowire: true
        public: true
        resource: '../../../src/LogManagement/*'
        # exclude: '../../../src/LogManagement/Domain/{Entity,UseCase,ValueObject}'
