services:

    Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder:
        arguments:
            $cost: 8

    
    AppCommon\:
        autowire: true
        public: true
        resource: '../../../src/AppCommon/*'
        exclude: '../../../src/AppCommon/Domain/{Entity,UseCase,ValueObject,Message}'
    AppCommon\Domain\ValueObject\:
        public: true
        resource: '../../../src/AppCommon/Domain/ValueObject/*'


    UserManagement\:
        autowire: true
        public: true
        resource: '../../../src/UserManagement/*'
        exclude: '../../../src/UserManagement/Domain/{Entity,UseCase,ValueObject,Message}'
    UserManagement\Domain\Entity\:
        public: true
        resource: '../../../src/UserManagement/Domain/Entity/*'
    UserManagement\Domain\Message\:
        public: true
        resource: '../../../src/UserManagement/Domain/Message/*'
    UserManagement\Domain\UseCase\:
        public: true
        resource: '../../../src/UserManagement/Domain/UseCase/*'
    UserManagement\Domain\ValueObject\:
        public: true
        resource: '../../../src/UserManagement/Domain/ValueObject/*'
    
    
    UserManagement\Infrastructure\Service\PasswordEncoderImpl:
        bind:
            Symfony\Component\Security\Core\Encoder\SelfSaltingEncoderInterface: '@Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder'
    UserManagement\Infrastructure\Service\UserSessionManagerImpl:
        bind:
            Symfony\Component\HttpFoundation\Session\SessionInterface: '@session'


    ExpenseManagement\:
        autowire: true
        public: true
        resource: '../../../src/ExpenseManagement/*'
        exclude: '../../../src/ExpenseManagement/Domain/{Entity,UseCase,ValueObject,Message}'
    ExpenseManagement\Domain\Entity\:
        public: true
        resource: '../../../src/ExpenseManagement/Domain/Entity/*'
    ExpenseManagement\Domain\Message\:
        public: true
        resource: '../../../src/ExpenseManagement/Domain/Message/*'
    ExpenseManagement\Domain\UseCase\:
        public: true
        resource: '../../../src/ExpenseManagement/Domain/UseCase/*'
    ExpenseManagement\Domain\ValueObject\:
        public: true
        resource: '../../../src/ExpenseManagement/Domain/ValueObject/*'


    DashboardManagement\:
        autowire: true
        public: true
        resource: '../../../src/DashboardManagement/*'


    # The Event Subscriber must be at the buttom list of other
    # bundle service registration to make sure all loaded before subscribing
    # to the event handler of symfony.
    AppCommon\Application\EventSubscriber\AuthenticationSubscriber:
        autowire: true
        tags: [kernel.event_subscriber]

